### ISSUE TITLE
Not working in React

### ISSUE THREAD

**Issue by krazziekay** [davidpelayo/orb-latest#3]
I just installed orb using npm, and get this error by simply importing orb:
![image](https://user-images.githubusercontent.com/13076255/26917043-55c9e588-4c4c-11e7-9ae4-cf6ac8c0d863.png)
Any ideas??

**Comment by davidpelayo** [comment]
The library (inherited from the original and still not refactored) uses `createClass` from the required package `React`. I guess there is some issue with your dependencies management?

Can you create a codepen, jsfiddle, plunker, jsbin or similar to reproduce it and see better the insights?

Thanks for reporting, @krazziekay.

**Comment by krazziekay** [comment]
I am trying to add it in a sample project of mine, which I have added on github, here is the link
https://github.com/krazziekay/toDoListUsingRedux
Please check it...

**Comment by davidpelayo** [comment]
You are using an old version of the library, as I can see on the [`package.json`](https://github.com/krazziekay/toDoListUsingRedux/blob/master/package.json#L7)...

**Comment by krazziekay** [comment]
do u mean old version of Orb.js?? how do i solve this?

**Comment by davidpelayo** [comment]
First, your orb dependency is the one maintained on [`orb` original repo](https://www.npmjs.com/package/orb), which doesn't have to do with this repo.

Regarding your second question, the version you use of `orb` and `react` aren't compatible. `orb` 1.0.9 is not fully compatible with `react` 15. Therefore it won't work. That said, you may also have issues with how you bundle your solution and how you expose variables to the global scope.

I recommend you, if you don't know how to proceed, to raise a ticket on Hackhands so some expert can help you doing screen sharing and so on.
